### ISSUE TITLE
Unclear phrasing, missing text, consistency

### ISSUE THREAD

**Issue by cristi-maco** [HackYourFuture/mentors#2]
Hi. While reading this document, I've noticed a few minor problems which would be nice to fix:

- usage of 'RePo' term - what does it mean, why is it spelled like that? it's just 'repo' from 'repository', or something else? It appears twice in the page (once at start and once near end)
 
- the 'Introduction' paragraph ends abruptly, is something missing there?: "If you have" (just that)

- invalid link here: " have developed a curriculum, which you can find _here_" - https://github.com/HackYourFuture/mentors/blob/main/www.github.com/hackyourfuture  ->  this I think is fixed in a currently open PR

- in 'Structure' paragraph: "Check the table at the top for an overview and explanation of the different volunteering roles." - which table at the top? (there is not table above, but there is one under it..)

- 'What we expect from you' paragraph - in the list after 'They can learn by example to:' should start all items in a consistent way, either lowercase or uppercase (now it's mixed)

- spelling of 'pro-active' - would it be better 'proactive' ? (seems the more common spelling)

**Comment by aminmarashi** [comment]
I addressed some of those points in my PR before finding this issue: https://github.com/HackYourFuture/mentors/pull/11

**Comment by Tjebbee** [comment]
thanks for the feedback! has been integrated :)
